### ISSUE TITLE
Initial review task list - 11/13-11/27

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [MargaretSiple-NOAA/goa-ai-data-reports#56]
This is a list of stuff I need help with while I'm gone! I would love to have input on Table 2 and a review of the 
If any of the following items are an issue and you complete them, feel free to close the issue! 

For more info on each of the list items, click on the issues that are linked to them. And LMK if you have any questions-- I won't be totally offline.

# Main needs

- [x] #53  -- does the R table match the SQL table? If not, let me know. SQL-produced table is at G:/GOA/GOA2023/DataReport/Table 2/Table 2.xlsx. 
- [x] #66
- [x] #41 -- double check language about IPHC sampling in the text. Is there sufficient detail? 
- [x] Review a draft of the data report in Word (link to doc is [here](https://docs.google.com/document/d/1koSQYir1RwqCILbO_uMCni41Uptg6SCF/edit?usp=drive_link&ouid=111519802483611531993&rtpof=true&sd=true)). Same review protocol as last year: if there are clear changes you need to make to the text, please incorporate them in the [google docs "MainText" files](https://drive.google.com/drive/folders/1UAQKChSuKohsRJ5enOloHPk3qFtk5kVC?usp=drive_link). Try not to make edits directly in the full draft, but if you must... that's ok. 
- [x] #60

# Bonus items 

- [x] Try running the whole report! Cool 🥇 . #55

**Comment by MargaretSiple-NOAA** [comment]
I just noticed a weird thing in the second table for each species (referred to in general as "table 4") where there's a random Aleutian row. OOPS. I will fix that!

**Comment by MargaretSiple-NOAA** [comment]
All these are done! Yay :)
